spring:
  profiles: 
    active: default
server: 
  port: 8801
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*" 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
